[package]
name = "vardel"
version = "0.1.0"
authors = ["Vincent Foley <vfoley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
proptest = "0.10"
